variables:
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_MEMORY_LIMIT: "2Gi"
  KUBERNETES_MEMORY_REQUEST: "2Gi"
include:
  - project: claranet/guildes/pipeline/python-templates/python-gitlab-ci-templates
    ref: v0.18.0
    file: poetry.yml
  - local: .gitlab-ci.custom.yml
